### ISSUE TITLE
Routing failing when visiting any page but index

### ISSUE THREAD

**Issue by kepford** [mattgrill/decoupled-dev-days#17]
If you visit a page like https://decoupleddevdays.com/sponsoring you will see a 404

## Steps to reproduce

Click on this link
https://decoupleddevdays.com/about
or this one
https://decoupleddevdays.com/sponsoring

**Comment by mrjmd** [comment]
I think this is obsolete now, the menu links properly link to paths with hashes, which can be reloaded. Ex. https://decoupleddevdays.com/#/sponsoring

We may want to consider getting rid of hash based paths, but that can be a separate issue if so.
